# This config file is set up to -

# execute scripts on your local machine in Chrome browser in desktop mode and default resolution:

configuration.profiles=web/desktop/chrome
web.driver.capabilities.chrome.prefs.credentials_enable_service=false
web.driver.capabilities.chrome.prefs.profile.password_manager_enabled=false
web.driver.capabilities.chrome.args=--disable-notifications
web.driver.capabilities.chrome.args=--disable-features=PasswordLeakDetection
web.driver.capabilities.chrome.args=--disable-features=PasswordManagerOnboarding

# pick up suite related properties from 'demo' suite folder:

configuration.suites=training

# pick up environment related properties from 'saucedemo' environment folder:

configuration.environments=saucedemo_Gitarin


